### PR TITLE
File types plugins architecture

### PR DESCRIPTION
**Pull request by roman-alexeev**
This separates logic for discovering, critiquing and editing files
to file type plugins, of which you can have several.
It also provides --ft-plugins|f switch to set the plugin set during init
command.

Currently the only plugin in this repo is perl5, which
behaves like old File.

### CODE REVIEW

**Comment by stevan** [comment]
This is a good start, but I have a few small issues with it.

To begin with, I think you could have broken this up into smaller commits, and in particular two bits look like they really should be separate pull-requests:

1. There is a `quick` flag feature that was added to the `process` command and is included in this commit. I assume that was an accident. 
2. I am a little confused as to why `filename_for_edit` and `filename_for_git_add` in `App::Critique::Session::File` do the exact same thing, but are two different subs. I assume this was because they might need to vary at some point, but it would be good if you could document this somewhere. Also, it is does not seem to be strongly coupled to the file type stuff and is generally useful so ideally is a separate PR.

Next I have a couple problems with the implementation: 

1. Please do not use `Module::Pluggable`, it is almost always more complex then is needed and is notorious for creating insanely difficult to follow code and unhelpful stack traces. In this case I think the code would be much easier to understand without `Module::Pluggable` and not suffer from a loss of functionality. 
2. I am a little concerned about the mixed calling conventions, for instance, within the `App::Critique::Session::FileType` package you have two, the `shortname` sub is called as a fully qualified function while the `matching_filetype` sub is called as a class method. Additionally the new `load_file` sub in `App::Critique::Session` is called as a function, but `App::Critique::Session` is a class.

Beyond this my only other issue is that I hate the word `Plugin`, so would prefer that it not show in the naming. In this case it is simply just adding support for multiple file types, no need to lay the groundwork for a plugins ecosystem, etc.

**Comment by roman-alexeev** [comment]
Good points, I'll work on them.
And yes, these two functions are different, because in the other plugin, which went to bcritical, makes use of the difference.

What term do you prefer instead of plugin?

**Comment by stevan** [comment]
> And yes, these two functions are different, because in the other plugin, which went to bcritical, makes use of the difference.

Can you document an example usage here? ... since the other tool is internal :)

> What term do you prefer instead of plugin?

I think `s/plugin//g` should do it, there is no need for the term at all. 

These are just "file types", the concept needs nothing more. In fact, if you just switch from `ft_plugins` to `file_types` it should do it for 90% of the cases. It also makes it more obvious what it is for, in this case the `plugin` part of the name overshadows the `ft` part, but switch to `file_types` and things are more obvious. Make sense?

**Comment by roman-alexeev** [comment]
Yep, sounds reasonable.

**Comment by roman-alexeev** [comment]
Updated as per your suggestions.

**Comment by stevan** [comment]
The only change is that I don't like `Module::Load` either, the best module for this is actually `Module::Runtime`, but I can make that myself when I merge it all in.

Thanks!

**Pull request merged**
