### PR TITLE
Implemented a App::Critique::Util::FileFilters to enable code reuse

### PR DESCRIPTION
**Pull request by stuartskelton**
This is a little rough and ready, needs some (being rather relative term) more work to polish and I apologies, and I am more than willing to bring it up to snuff.

The idea behind this is to remove some duplicate code, by rolling up any file filtering into single module, as I could see myself wanting to prune on a min/max number of issues, or just pruning on a given issue, so instead, so a user could hone on a single issue.

It is rather naughty (am still rather new to App::Cmd, and suspect I may grow to like it a lot), and I probably should have gone the route of a plug-in, but I wanted to keep the name space a little cleaner.

### CODE REVIEW

**Comment by stevan** [comment]
I see where you are going on this, and I agree with your motivation, but I would like to hold off on merging it for the moment. 

My main reasoning is that I would like to take some time to better generalize these filters and turn them into `App::Cmd::Plugins` instead. I hear your concerns about namespace pollution, but given that `execute` is really the only subroutine in an `App::Cmd::Command` that matters, it shouldn't be an issue.

**Comment by stuartskelton** [comment]
I totally agree with why you would want to hold off merging this.   Originally I planned to make this a plugin similar to `App::Critique::Plugin::UI`, and export the subroutines under a prefix of `file_filter_xyz`.

Converting this to a plugin shouldn't be to much of a hardship, and when I can steal some time, Ill push a completing PR.

**Comment by stevan** [comment]
That works for me actually, if they are nicely namespaced  then we can worry about further generalizing them at a later point. 

I think the only thing I would add is that I think we should do a `success` and an `error` callback for them so that we do not need to bother with importing `App::Critique::Plugin::UI` into the new plugin. However not having this would not be a blocker for the plugin conversion.

Also, for the time being I think it is best to the underscore prefixed version of the `App::Critique::Plugin::UI` functions (https://github.com/stevan/p5-App-Critique/blob/master/lib/App/Critique/Plugin/UI.pm#L36-L64) so that you don't need to pass in the first two arguments unnecessarily.

**Comment by stevan** [comment]
Closing as this is superseded by #11

**Pull request closed without merging**
